# Site
repository: bum752/resume
favicon: images/favicon.ico

# Personal info
name: 신주범
title: 백엔드 엔지니어
email: bum752@gmail.com
website: https://bum752.github.io

# Social links
# twitter_username: facespics
github_username:  bum752
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: jubeom
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  <mark>Spring Boot</mark>, <mark>Node.js</mark>를 이용한 백엔드 개발을 합니다!
  
  <mark>MSA</mark>와 <mark>AWS</mark>를 이용한 인프라 구성에도 관심이 많습니다.
  
  <mark>쿠버네티스</mark>를 공부 중입니다.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
more_title: Awards
more_content: | # this will include new lines to allow paragraphs
   - 제 2회 부산 ICT 융합 해카톤 대상(부산광역시장상)
   - 제 5회 SW융합 해커톤 대회 대상(과학기술정보통신부 장관상)

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
